fetch_lambda_function_name = 'reddit_fetch_and_store'
nsfw_lambda_function_name = 'nsfwLambda'
rule_lambda_function_name = 'ruleLambda'
#nsfw_processing_url = 'http://ec2-3-142-240-168.us-east-2.compute.amazonaws.com:5000/classify'
nsfw_processing_url = 'http://ec2-3-142-240-168.us-east-2.compute.amazonaws.com:5000/classify'